CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'admin_user') THEN
CREATE ROLE admin_user LOGIN PASSWORD 'test123456';
END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'catalog_user') THEN
CREATE ROLE catalog_user LOGIN PASSWORD 'test1234';
END IF;
END$$;

GRANT CONNECT ON DATABASE catalog TO admin_user;
GRANT CONNECT ON DATABASE catalog TO catalog_user;

GRANT USAGE, CREATE ON SCHEMA public TO admin_user;
GRANT USAGE ON SCHEMA public TO catalog_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO catalog_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO catalog_user;

ALTER DEFAULT PRIVILEGES FOR ROLE admin_user IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO catalog_user;

ALTER DEFAULT PRIVILEGES FOR ROLE admin_user IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO catalog_user;
