POST http://localhost:8080/price-integration/prices
Content-Type: application/json

{
  "requestId": "req-0004",
  "productId": "f3dfaef1-9dab-45d7-abec-c8fdd4f1fe74",
  "priceInCents": 123456789,
  "currency": "EUR",
  "effectiveAt": "2026-02-23T21:05:00Z",
  "source": "price-integration"
}
