PUT http://localhost:8080/products/f3dfaef1-9dab-45d7-abec-c8fdd4f1fe74
Content-Type: application/json

{
  "name": "Tesla Model S Plaid",
  "description": "Updated description 1",
  "currency": "EUR",
  "attributes": {
    "color": "red",
    "paint": "metallic"
  }
}
